### ISSUE TITLE
Bad state: Stream has already been listened to. Duplicate GlobalKey detected in widget tree.

### ISSUE THREAD

**Issue by omidraha** [RaviKavaiya/sliding_panel#23]
When I want to use `StreamBuilder` inside of `panelContent`, 
I get this error:

```
Bad state: Stream has already been listened to. 
Duplicate GlobalKey detected in widget tree.
```

Here is sample [code](https://github.com/omidraha/modal_example/blob/master/lib/main.dart) and sample [project](https://github.com/omidraha/modal_example).

Related [issue](https://github.com/flutter/flutter/issues/13780#issuecomment-683331039).
 
Traceback:
```
I/flutter ( 4618): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 4618): The following StateError was thrown building NotificationListener<KeepAliveNotification>:
I/flutter ( 4618): Bad state: Stream has already been listened to.
I/flutter ( 4618): The relevant error-causing widget was:
I/flutter ( 4618):   SliverList
I/flutter ( 4618):   file:///sdk/flutter/.pub-cache/hosted/pub.dartlang.org/sliding_panel-1.3.1/lib/src/panel.dart:1004:27
I/flutter ( 4618): When the exception was thrown, this was the stack:
I/flutter ( 4618): #3      _StreamBuilderBaseState._subscribe (package:flutter/src/widgets/async.dart:139:37)
I/flutter ( 4618): #4      _StreamBuilderBaseState.initState (package:flutter/src/widgets/async.dart:113:5)
I/flutter ( 4618): #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4697:58)
I/flutter ( 4618): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4533:5)
I/flutter ( 4618): ...     Normal element mounting (33 frames)
I/flutter ( 4618): #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3503:14)
I/flutter ( 4618): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:3262:18)
I/flutter ( 4618): #41     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1157:36)
I/flutter ( 4618): #42     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1142:20)
I/flutter ( 4618): #43     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2622:19)
I/flutter ( 4618): #44     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1135:11)
I/flutter ( 4618): #45     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:356:23)
I/flutter ( 4618): #46     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1879:58)
I/flutter ( 4618): #47     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:927:15)
I/flutter ( 4618): #48     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1879:13)
I/flutter ( 4618): #49     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:345:5)
I/flutter ( 4618): #50     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:429:5)
I/flutter ( 4618): #51     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:81:12)
I/flutter ( 4618): #52     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
I/flutter ( 4618): #53     RenderProxySliver.performLayout (package:flutter/src/rendering/proxy_sliver.dart:54:11)
I/flutter ( 4618): #54     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
I/flutter ( 4618): #55     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:471:13)
I/flutter ( 4618): #56     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1466:12)
I/flutter ( 4618): #57     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1375:20)
I/flutter ( 4618): #58     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
I/flutter ( 4618): #59     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter ( 4618): #60     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
I/flutter ( 4618): #61     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter ( 4618): #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
I/flutter ( 4618): #63     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter ( 4618): #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
I/flutter ( 4618): #65     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter ( 4618): #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
I/flutter ( 4618): #67     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter ( 4618): #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
I/flutter ( 4618): #69     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter ( 4618): #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
I/flutter ( 4618): #71     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter ( 4618): #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
I/flutter ( 4618): #73     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter ( 4618): #74     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
I/flutter ( 4618): #75     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter ( 4618): #76     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
I/flutter ( 4618): #77     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter ( 4618): #78     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
I/flutter ( 4618): #79     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter ( 4618): #80     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
I/flutter ( 4618): #81     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:562:15)
I/flutter ( 4618): #82     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
I/flutter ( 4618): #83     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter ( 4618): #84     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
I/flutter ( 4618): #85     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:270:13)
I/flutter ( 4618): #86     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
I/flutter ( 4618): #87     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:209:11)
I/flutter ( 4618): #88     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
I/flutter ( 4618): #89     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:562:15)
I/flutter ( 4618): #90     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
I/flutter ( 4618): #91     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter ( 4618): #92     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
I/flutter ( 4618): #93     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter ( 4618): #94     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
I/flutter ( 4618): #95     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:304:13)
I/flutter ( 4618): #96     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
I/flutter ( 4618): #97     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter ( 4618): #98     RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
I/flutter ( 4618): #99     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter ( 4618): #100    RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
I/flutter ( 4618): #101    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter ( 4618): #102    RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
I/flutter ( 4618): #103    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter ( 4618): #104    RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
I/flutter ( 4618): #105    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter ( 4618): #106    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3263:13)
I/flutter ( 4618): #107    RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
I/flutter ( 4618): #108    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
I/flutter ( 4618): #109    RenderObject.layout (package:flutter/src/rendering/object.dart:1776:7)
I/flutter ( 4618): #110    _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:702:15)
I/flutter ( 4618): #111    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1639:7)
I/flutter ( 4618): #112    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:896:18)
I/flutter ( 4618): #113    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:404:19)
I/flutter ( 4618): #114    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:881:13)
I/flutter ( 4618): #115    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
I/flutter ( 4618): #116    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1114:15)
I/flutter ( 4618): #117    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1053:9)
I/flutter ( 4618): #118    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:969:5)
I/flutter ( 4618): #122    _invoke (dart:ui/hooks.dart:253:10)
I/flutter ( 4618): #123    _drawFrame (dart:ui/hooks.dart:211:3)
I/flutter ( 4618): (elided 6 frames from dart:async)
I/flutter ( 4618): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 4618): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 265 pos 16: 'child == null || indexOf(child) > index': is not true.
I/flutter ( 4618): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 265 pos 16: 'child == null || indexOf(child) > index': is not true.
I/flutter ( 4618): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 265 pos 16: 'child == null || indexOf(child) > index': is not true.
I/flutter ( 4618): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 2626 pos 20: '_debugCurrentBuildTarget == context': is not true.
I/flutter ( 4618): Another exception was thrown: NoSuchMethodError: The method 'debugAssertIsValid' was called on null.
I/flutter ( 4618): Another exception was thrown: NoSuchMethodError: The method 'debugAssertIsValid' was called on null.
I/flutter ( 4618): Another exception was thrown: NoSuchMethodError: The getter 'visible' was called on null.
I/flutter ( 4618): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 265 pos 16: 'child == null || indexOf(child) > index': is not true.
I/flutter ( 4618): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 265 pos 16: 'child == null || indexOf(child) > index': is not true.
I/flutter ( 4618): Another exception was thrown: Duplicate GlobalKey detected in widget tree.
I/flutter ( 4618): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 5879 pos 12: 'child == _child': is not true.
I/flutter ( 4618): Another exception was thrown: Duplicate GlobalKey detected in widget tree.
I/flutter ( 4618): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 5879 pos 12: 'child == _child': is not true.
I/flutter ( 4618): Another exception was thrown: Duplicate GlobalKey detected in widget tree.
I/flutter ( 4618): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 5879 pos 12: 'child == _child': is not true.
I/flutter ( 4618): Another exception was thrown: Duplicate GlobalKey detected in widget tree.
I/flutter ( 4618): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 5879 pos 12: 'child == _child': is not true.
I/flutter ( 4618): Another exception was thrown: Duplicate GlobalKey detected in widget tree.
I/flutter ( 4618): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 5879 pos 12: 'child == _child': is not true.
I/flutter ( 4618): Another exception was thrown: Duplicate GlobalKey detected in widget tree.
I/flutter ( 4618): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 5879 pos 12: 'child == _child': is not true.
I/flutter ( 4618): Another exception was thrown: Duplicate GlobalKey detected in widget tree.
I/flutter ( 4618): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 5879 pos 12: 'child == _child': is not true.
I/flutter ( 4618): Another exception was thrown: Duplicate GlobalKey detected in widget tree.
I/flutter ( 4618): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 5879 pos 12: 'child == _child': is not true.
I/flutter ( 4618): Another exception was thrown: Duplicate GlobalKey detected in widget tree.
I/flutter ( 4618): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 5879 pos 12: 'child == _child': is not true.
I/flutter ( 4618): Another exception was thrown: Duplicate GlobalKey detected in widget tree.
I/flutter ( 4618): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 5879 pos 12: 'child == _child': is not true.
I/flutter ( 4618): Another exception was thrown: Duplicate GlobalKey detected in widget tree.
I/flutter ( 4618): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 5879 pos 12: 'child == _child': is not true.
I/flutter ( 4618): Another exception was thrown: Duplicate GlobalKey detected in widget tree.
I/flutter ( 4618): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 5879 pos 12: 'child == _child': is not true.
I/flutter ( 4618): Another exception was thrown: Duplicate GlobalKey detected in widget tree.
I/flutter ( 4618): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 5879 pos 12: 'child == _child': is not true.
I/flutter ( 4618): Another exception was thrown: Duplicate GlobalKey detected in widget tree.
I/flutter ( 4618): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 5879 pos 12: 'child == _child': is not true.
I/flutter ( 4618): Another exception was thrown: Duplicate GlobalKey detected in widget tree.


```

**Comment by RaviKavaiya** [comment]
Hi @omidraha ...

This seems to be unrelated to sliding_panel.
First, the streambuilder is in different route. So, rebuild will also add another subscription to the stream.

Moreover, the stream you have created is a single subscription stream, that's causing the problem...

Solution (I have not tested but try and please tell me):
Try giving a Key to your widget tree that rebuilds.
Or, convert to a broadcast stream.
For details, look here:
https://stackoverflow.com/questions/51396769/flutter-bad-state-stream-has-already-been-listened-to

**Comment by RaviKavaiya** [comment]
@omidraha any updates on this?
