### ISSUE TITLE
Disposing Controller crashing the app on Navigator Pop

### ISSUE THREAD

**Issue by alvinvin00** [RaviKavaiya/sliding_panel#4]
when Sliding Panel showed up, this exception happens

```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
ScrollableState#ca85e(tickers: tracking 1 ticker, position: _PanelScrollPosition#c9215(offset: 0.0, range: 0.0..1.0, viewport: 77.0, ScrollableState, ClampingScrollPhysics, null, ScrollDirection.idle)) was disposed with an active Ticker.

ScrollableState created a Ticker via its TickerProviderStateMixin, but at the time dispose() was called on the mixin, that Ticker was still active. All Tickers must be disposed before calling super.dispose(). Tickers used by AnimationControllers should be disposed by calling dispose() on the AnimationController itself. Otherwise, the ticker will leak.
The offending ticker was: _WidgetTicker(created by ScrollableState#ca85e(tickers: tracking 0 tickers, position: _PanelScrollPosition#c9215(offset: 0.0, range: 0.0..1.0, viewport: 77.0, ScrollableState, ClampingScrollPhysics, IdleScrollActivity#443f8, ScrollDirection.idle)))
The stack trace when the _WidgetTicker was actually created was:
#0      new Ticker.<anonymous closure> (package:flutter/src/scheduler/ticker.dart:64:40)
#1      new Ticker (package:flutter/src/scheduler/ticker.dart:66:6)
#2      new _WidgetTicker (package:flutter/src/widgets/ticker_provider.dart:225:80)
#3      TickerProviderStateMixin.createTicker (package:flutter/src/widgets/ticker_provider.dart:161:34)
#4      new AnimationController (package:flutter/src/animation/animation_controller.dart:245:21)
#5      _setPanelPosition (package:sliding_panel/src/utils.dart:260:33)
<asynchronous suspension>
#6      PanelController.collapse (package:sliding_panel/src/controller.dart:107:13)
<asynchronous suspension>
#7      _OrderPageState.buildGoogleMap.<anonymous closure> (package:sg_mobile/ui/order/order_page.dart:91:26)
#8      _GoogleMapState.onPlatformViewCreated (package:google_maps_flutter/src/google_map.dart:296:14)
<asynchronous suspension>
#9      AndroidViewController._create (package:flutter/src/services/platform_views.dart:643:15)
<asynchronous suspension>
#10     AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:557:14)
<asynchronous suspension>
#11     RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174:29)
<asynchronous suspension>
#12     RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155:5)
#13     RenderObject.layout (package:flutter/src/rendering/object.dart:1686:9)
#14     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
#15     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
#16     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:549:15)
#17     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
#18     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:242:13)
#19     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
#20     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
#21     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
#22     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
#23     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:444:7)
#24     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
#25     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
#26     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
#27     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#28     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
#29     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#30     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1232:11)
#31     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
#32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#33     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
#34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#35     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
#36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#37     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
#38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#39     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
#40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#41     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
#42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#43     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
#44     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#45     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
#46     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3138:14)
#47     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
#48     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
#49     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1578:7)
#50     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:844:18)
#51     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:341:19)
#52     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:761:13)
#53     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:280:5)
#54     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1033:15)
#55     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:975:9)
#56     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:891:5)
#60     _invoke (dart:ui/hooks.dart:249:10)
#61     _drawFrame (dart:ui/hooks.dart:207:3)
(elided 3 frames from package dart:async)

When the exception was thrown, this was the stack: 
#0      TickerProviderStateMixin.dispose.<anonymous closure> (package:flutter/src/widgets/ticker_provider.dart:178:13)
#1      TickerProviderStateMixin.dispose (package:flutter/src/widgets/ticker_provider.dart:191:6)
#2      ScrollableState.dispose (package:flutter/src/widgets/scrollable.dart:370:11)
#3      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4142:12)
#4      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1738:13)
...
```

when a page got disposed by Back button, i got this

```
════════ (2) Exception caught by widgets library ═══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 1773 pos 12: '_elements.contains(element)': is not true.
User-created ancestor of the error-causing widget was: 
  ScrollConfiguration file:///C:/Project%20Android%20Studio/Starguard/sg_mobile/lib/app.dart:14:18
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (3) Exception caught by widgets library ═══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 1773 pos 12: '_elements.contains(element)': is not true.
User-created ancestor of the error-causing widget was: 
  ScrollConfiguration file:///C:/Project%20Android%20Studio/Starguard/sg_mobile/lib/app.dart:14:18
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (4) Exception caught by widgets library ═══════════════════════════════════════════════════
The getter 'userGestureInProgress' was called on null.
Receiver: null
Tried calling: userGestureInProgress
User-created ancestor of the error-causing widget was: 
  ScrollConfiguration file:///C:/Project%20Android%20Studio/Starguard/sg_mobile/lib/app.dart:14:18
════════════════════════════════════════════════════════════════════════════════════════════════════
```

Strangely that only happened in Debug build, either they hid it on Release build or something wrong with AnimationController not getting disposed

**Comment by RaviKavaiya** [comment]
Thanks.
Can you please share a minimal code that reproduces this issue? That would be very much useful for me to find the bug.

**Comment by alvinvin00** [comment]
This is my implementation of Sliding Panel (there is some bool variable that i use on the parameter which i don't include with this snippet)

`
    return SlidingPanel(
      curve: Curves.fastOutSlowIn,
      backPressBehavior: BackPressBehavior.COLLAPSE_POP,
      backdropConfig: BackdropConfig(
        enabled: true,
        effectInCollapsedMode: isSearching,
        closeOnTap: false,
      ),
      panelController: _panelController,
      initialState: InitialPanelState.closed,
      isDraggable: isSearching || selectedPlaces == null,
      isTwoStatePanel: false,
      parallaxSlideAmount: 0,
      decoration: PanelDecoration(
          padding: EdgeInsets.only(
            top: 8,
            left: 8,
            right: 8,
          ),
          borderRadius: BorderRadius.only(
            topLeft: Radius.circular(16),
            topRight: Radius.circular(16),
          )),
      size: PanelSize(collapsedHeight: 0.3, expandedHeight: 1, closedHeight: 0),
      autoSizing: PanelAutoSizing(autoSizeCollapsed: selectedPlaces != null),
      snapPanel: true,
      content: PanelContent(
          panelContent: (context, sc) =>
              SingleChildScrollView(
                controller: sc,
                child: buildPanel(order, context),
              ),
          bodyContent: Stack(children: <Widget>[
            buildGoogleMap(),
            Positioned(
              left: 8,
              right: 8,
              top: 8,
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: <Widget>[
                  FloatingActionButton(
                    onPressed: () {
                      Navigator.pop(context);
                    },
                    heroTag: null,
                    child: Icon(Icons.arrow_back),
                  ),
                  FloatingActionButton(
                    onPressed: () {
                      MapService().currentPosition.then((pos) {
                        animateCameraToPosition(pos);
                      });
                    },
                    heroTag: null,
                    child: Icon(Icons.my_location),
                  )
                ],
              ),
            )
          ])),
    );
`

The issue only happened when the panel disappeared from screen (in my code, when the panel is on closedState since i set the closedSize at 0)

Sorry for formatting errors

**Comment by RaviKavaiya** [comment]
@alvinvin00  sorry for the late reply...

I tried your example with Flutter version ```1.9.1+hotfix.6``` (stable) on 2 different Android emulators as well as a Physical device.

I did not get any exception while opening, dragging the panel, as well as pressing the back button.
I also have posted the code I tried below. In your code, some of the lines were not understood by me, those are commented.

Moreover, you did not use the ```ScrollController``` you got on ```panelContent``` argument (on line 60 in my code). Check that. That *may* cause problems.

I also have put an additional ```FloatingActionButton``` to expand the panel.

Conclusion: 
As your previous code was not sufficient to reproduce the issue, check out my code. If you have any different code than mine and still getting issue, please share it.

If your issue is resolved, then please tell what was wrong here and close the issue. (So that others can avoid mistakes)

**Comment by RaviKavaiya** [comment]
```dart
import 'package:flutter/material.dart';
import 'package:sliding_panel/sliding_panel.dart';

class TestExample extends StatefulWidget {
  @override
  _TestExampleState createState() => _TestExampleState();
}

class _TestExampleState extends State<TestExample> {
  PanelController pc;

  @override
  void initState() {
    super.initState();

    pc = PanelController();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Test'),
      ),
      body: SlidingPanel(
        curve: Curves.fastOutSlowIn,
        backPressBehavior: BackPressBehavior.COLLAPSE_POP,
        backdropConfig: BackdropConfig(
          enabled: true,
//          effectInCollapsedMode: isSearching,
          effectInCollapsedMode: true,
          closeOnTap: false,
        ),
        panelController: pc,
        initialState: InitialPanelState.closed,
//        isDraggable: isSearching || selectedPlaces == null,
        isDraggable: true,
        isTwoStatePanel: false,
        parallaxSlideAmount: 0,
        decoration: PanelDecoration(
          padding: EdgeInsets.only(
            top: 8,
            left: 8,
            right: 8,
          ),
          borderRadius: BorderRadius.only(
            topLeft: Radius.circular(16),
            topRight: Radius.circular(16),
          ),
        ),
        size:
            PanelSize(collapsedHeight: 0.3, expandedHeight: 1, closedHeight: 0),
//        autoSizing: PanelAutoSizing(autoSizeCollapsed: selectedPlaces != null),
        autoSizing:
            PanelAutoSizing(autoSizeCollapsed: true, autoSizeExpanded: true),
        snapPanel: true,
        content: PanelContent(
          panelContent: (context, sc) => SingleChildScrollView(
            controller: sc,
//            child: buildPanel(order, context),
            // !!!!! PROBLEM MAY BE HERE !!!!!
            child: ListView(
              shrinkWrap: true,
              controller: sc,
              children: <Widget>[
                Container(
                  padding: EdgeInsets.symmetric(vertical: 16),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    children: <Widget>[
                      Container(
                        margin: EdgeInsets.only(top: 16.0),
                        child: Text(
                          'Some list',
                          style: Theme.of(context).textTheme.headline,
                        ),
                      ),
                      Divider(
                        color: Colors.black,
                        height: 32,
                      ),
                      Material(
                        type: MaterialType.transparency,
                        child: Container(
                          padding: EdgeInsets.symmetric(horizontal: 12),
                          child: ListView(
                            shrinkWrap: true,
                            physics: ClampingScrollPhysics(),
                            children: <Widget>[
                              ListTile(
                                onTap: () {
                                  pc.popWithResult(result: 'Pizza');
                                },
                                title: Text(
                                  'Pizza',
                                  style: Theme.of(context).textTheme.title,
                                ),
                              ),
                              ListTile(
                                onTap: () {
                                  pc.popWithResult(result: 'Sandwich');
                                },
                                title: Text(
                                  'Sandwich',
                                  style: Theme.of(context).textTheme.title,
                                ),
                              ),
                              ListTile(
                                onTap: () {
                                  pc.sendResult(result: 'Pasta');
                                },
                                title: Text(
                                  'Pasta',
                                  style: Theme.of(context).textTheme.title,
                                ),
                              ),
                              ListTile(
                                onTap: () {
                                  pc.popWithResult(result: 'Punjabi');
                                },
                                title: Text(
                                  'Punjabi',
                                  style: Theme.of(context).textTheme.title,
                                ),
                              ),
                              ListTile(
                                onTap: () {
                                  pc.popWithResult(result: 'French Fries');
                                },
                                title: Text(
                                  'French Fries',
                                  style: Theme.of(context).textTheme.title,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),
          bodyContent: Stack(
            children: <Widget>[
//              buildGoogleMap(),
              Positioned(
                left: 8,
                right: 8,
                top: 8,
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: <Widget>[
                    FloatingActionButton(
                      onPressed: () {
                        Navigator.pop(context);
                      },
                      heroTag: null,
                      child: Icon(Icons.arrow_back),
                    ),
                    FloatingActionButton(
                      onPressed: () {},
                      heroTag: null,
                      child: Icon(Icons.my_location),
                    ),
                    FloatingActionButton(
                      onPressed: () {
                        pc.expand();
                      },
                      heroTag: null,
                      child: Icon(Icons.open_in_new),
                    ),
                  ],
                ),
              )
            ],
          ),
        ),
      ),
    );
  }
}

```

**Comment by RaviKavaiya** [comment]
@alvinvin00 Before talking about my plugin, I think you should LEARN GitHub basics.
You posted your issue on ALL the previous issues as well.

I would suggest you that, if you don't even know such basics, then please stop using these things.
